name: course_project
description: "Flutter course project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  # core
  freezed_annotation: ^2.4.1
  flutter_bloc: ^8.1.3
  bloc_concurrency: ^0.2.2
  intl: ^0.18.1
  slang: 3.26.2
  slang_flutter: 3.26.2
  get_it: ^7.6.4
  pull_to_refresh: ^2.0.0
  collection: ^1.17.2
  logger: ^2.0.2
  shimmer: ^3.0.0
  either_dart: ^1.0.0
  dartx: ^1.2.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  palestine_console: ^0.0.10
  equatable: ^2.0.5
  path_provider: ^2.1.1
  freezed: ^2.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  slang_build_runner: 3.26.2
  json_serializable: ^6.7.1
  freezed: ^2.4.5
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true
